name: zeta-particle
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy==1.26.4
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - scipy==1.14.1
      - plotly==5.24.1
      - sympy==1.13.3
